import { series } from "../TypeScript/types";


export const images: series[] = [
    {
        id: 'misha',
        genre: null,
        titleImg: '/images/thumbnails/misha.png',
        images: [
            '/images/Misha/Misha1.jpg',
            '/images/Misha/Misha2.jpg',
            '/images/Misha/Misha3.jpg', 
            '/images/Misha/Misha4.jpg',
        ],
        wideImages: [
            '/images/Misha/Misha0.jpg',
        ]
    },
    {
        id: 'iliya',
        genre: null,
        titleImg: '/images/thumbnails/iliya.png',
        images: [
            '/images/Iliya/Iliya1.jpg',
            '/images/Iliya/Iliya2.jpg',
            '/images/Iliya/Iliya3.jpg', 
            '/images/Iliya/Iliya4.jpg',
            '/images/Iliya/Iliya5.jpg',
            '/images/Iliya/Iliya6.jpg',
            '/images/Iliya/Iliya7.jpg',
            '/images/Iliya/Iliya8.jpg',
            
        ],
        wideImages: [
            '/images/Iliya/Iliya0.jpg',
        ],
    },
    {
        id: 'ren',
        genre: null,
        titleImg: '/images/thumbnails/ren.png',
        images: [
            '/images/Ren/Ren0.jpg',
            '/images/Ren/Ren1.jpg',
            '/images/Ren/Ren2.jpg',
            '/images/Ren/Ren3.jpg', 
            '/images/Ren/Ren4.jpg'
        ],
        wideImages: [''],
    },
    {
        id: 'vanya',
        genre: null,
        titleImg: '/images/thumbnails/vanya.png',
        images: [
            '/images/Vanya/Vanya0.jpg',
            '/images/Vanya/Vanya1.jpg',
            '/images/Vanya/Vanya2.jpg',
            '/images/Vanya/Vanya3.jpg', 
            '/images/Vanya/Vanya4.jpg',
            '/images/Vanya/Vanya5.jpg',
            '/images/Vanya/Vanya6.jpg',
            '/images/Vanya/Vanya7.jpg',
            '/images/Vanya/Vanya8.jpg', 
            '/images/Vanya/Vanya9.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'katya',
        genre: 'beauty',
        titleImg: '/images/thumbnails/katya.png',
        images: [
            '/images/Beauty/Katya/Katya0.jpg', 
            '/images/Beauty/Katya/Katya1.jpg',
            '/images/Beauty/Katya/Katya2.jpg',
            '/images/Beauty/Katya/Katya3.jpg',
            '/images/Beauty/Katya/Katya4.jpg',
            '/images/Beauty/Katya/Katya5.jpg',
            '/images/Beauty/Katya/Katya6.jpg',
            '/images/Beauty/Katya/Katya7.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'alina',
        genre: 'beauty',
        titleImg: '/images/thumbnails/alina.png',
        images: [
            '/images/Beauty/Alina/Alina0.jpg', 
            '/images/Beauty/Alina/Alina1.jpg',
            '/images/Beauty/Alina/Alina2.jpg',
            '/images/Beauty/Alina/Alina3.jpg',
            '/images/Beauty/Alina/Alina4.jpg',
            '/images/Beauty/Alina/Alina5.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'lena',
        genre: 'beauty',
        titleImg: '/images/thumbnails/lena.png',
        images: [
            '/images/Beauty/Lena/Lena0.jpg', 
            '/images/Beauty/Lena/Lena1.jpg',
            '/images/Beauty/Lena/Lena2.jpg',
            '/images/Beauty/Lena/Lena3.jpg',
            '/images/Beauty/Lena/Lena4.jpg',
            '/images/Beauty/Lena/Lena5.jpg',
            '/images/Beauty/Lena/Lena6.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'polina',
        genre: 'modeltests',
        titleImg: '/images/thumbnails/polina.png',
        images: [
            '/images/ModelTests/Polina/Polina0.jpg',
            '/images/ModelTests/Polina/Polina1.jpg',
            '/images/ModelTests/Polina/Polina2.jpg',
            '/images/ModelTests/Polina/Polina3.jpg', 
            '/images/ModelTests/Polina/Polina4.jpg',
            '/images/ModelTests/Polina/Polina5.jpg',
            '/images/ModelTests/Polina/Polina6.jpg',
            '/images/ModelTests/Polina/Polina7.jpg',
            '/images/ModelTests/Polina/Polina8.jpg', 
            '/images/ModelTests/Polina/Polina9.jpg',
            '/images/ModelTests/Polina/Polina10.jpg',
            '/images/ModelTests/Polina/Polina11.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'stacey',
        genre: 'modeltests',
        titleImg: '/images/thumbnails/stacey.png',
        images: [
            '/images/ModelTests/StaseyPMB/Stacey0.jpg',
            '/images/ModelTests/StaseyPMB/Stacey1.jpg',
            '/images/ModelTests/StaseyPMB/Stacey2.jpg', 
            '/images/ModelTests/StaseyPMB/Stacey4.jpg',
            '/images/ModelTests/StaseyPMB/Stacey5.jpg',
            '/images/ModelTests/StaseyPMB/Stacey6.jpg',
            '/images/ModelTests/StaseyPMB/Stacey7.jpg',
            '/images/ModelTests/StaseyPMB/Stacey8.jpg', 
            '/images/ModelTests/StaseyPMB/Stacey9.jpg',
            '/images/ModelTests/StaseyPMB/Stacey11.jpg',
            '/images/ModelTests/StaseyPMB/Stacey12.jpg',
            '/images/ModelTests/StaseyPMB/Stacey13.jpg', 
            '/images/ModelTests/StaseyPMB/Stacey14.jpg',
            '/images/ModelTests/StaseyPMB/Stacey15.jpg',
            '/images/ModelTests/StaseyPMB/Stacey16.jpg',
            '/images/ModelTests/StaseyPMB/Stacey17.jpg',
            '/images/ModelTests/StaseyPMB/Stacey18.jpg',
            '/images/ModelTests/StaseyPMB/Stacey19.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'zelda',
        genre: 'beauty',
        titleImg: '/images/thumbnails/zelda.png',
        images: [
            '/images/Beauty/Zelda/Zelda0.jpg', 
            '/images/Beauty/Zelda/Zelda1.jpg',
            '/images/Beauty/Zelda/Zelda2.jpg',
            '/images/Beauty/Zelda/Zelda3.jpg',
            '/images/Beauty/Zelda/Zelda4.jpg',
            '/images/Beauty/Zelda/Zelda5.jpg',
            '/images/Beauty/Zelda/Zelda6.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'violleta',
        genre: null,
        titleImg: '/images/thumbnails/violetta.png',
        images: [
            '/images/Violletta/Violleta0.jpg',
            '/images/Violletta/Violleta1.jpg',
            '/images/Violletta/Violleta2.jpg',
            '/images/Violletta/Violleta3.jpg', 
            '/images/Violletta/Violleta4.jpg',
            '/images/Violletta/Violleta5.jpg',
            '/images/Violletta/Violleta6.jpg',
            '/images/Violletta/Violleta7.jpg',
            '/images/Violletta/Violleta8.jpg', 
            '/images/Violletta/Violleta9.jpg',
            '/images/Violletta/Violleta10.jpg',
            '/images/Violletta/Violleta11.jpg',
            '/images/Violletta/Violleta12.jpg',
            '/images/Violletta/Violleta13.jpg', 
            '/images/Violletta/Violleta14.jpg',
            '/images/Violletta/Violleta15.jpg',
            '/images/Violletta/Violleta16.jpg', 
        ],
        wideImages: ['/images/Violletta/Violleta17.jpg',],
    },
    {
        id: 'raisa',
        genre: 'beauty',
        titleImg: '/images/thumbnails/raisa.png',
        images: [
            '/images/Beauty/Raisa/Raisa0.jpg', 
            '/images/Beauty/Raisa/Raisa1.jpg',
            '/images/Beauty/Raisa/Raisa2.jpg',
            '/images/Beauty/Raisa/Raisa3.jpg',
            '/images/Beauty/Raisa/Raisa4.jpg',
            '/images/Beauty/Raisa/Raisa5.jpg',
            '/images/Beauty/Raisa/Raisa6.jpg',
            '/images/Beauty/Raisa/Raisa7.jpg',
            '/images/Beauty/Raisa/Raisa8.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'b221120',
        genre: 'beauty',
        titleImg: '/images/thumbnails/b221120.png',
        images: [
            '/images/Beauty/b221120/b221120_0.jpg', 
            '/images/Beauty/b221120/b221120_1.jpg',
            '/images/Beauty/b221120/b221120_2.jpg',
            '/images/Beauty/b221120/b221120_3.jpg',
            '/images/Beauty/b221120/b221120_4.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'nand',
        genre: 'beauty',
        titleImg: '/images/thumbnails/nand.png',
        images: [
            '/images/Beauty/nand/NandD0.jpg', 
            '/images/Beauty/nand/NandD1.jpg',
            '/images/Beauty/nand/NandD2.jpg',
            '/images/Beauty/nand/NandD3.jpg',
            '/images/Beauty/nand/NandD4.jpg',
            '/images/Beauty/nand/NandD5.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'anya',
        genre: 'beauty',
        titleImg: '/images/thumbnails/anya.png',
        images: [
            '/images/Beauty/Anya/Anya0.jpg', 
            '/images/Beauty/Anya/Anya1.jpg',
            '/images/Beauty/Anya/Anya2.jpg',
            '/images/Beauty/Anya/Anya3.jpg',
            '/images/Beauty/Anya/Anya4.jpg',
            '/images/Beauty/Anya/Anya5.jpg',
            '/images/Beauty/Anya/Anya6.jpg',
            '/images/Beauty/Anya/Anya7.jpg',
            '/images/Beauty/Anya/Anya8.jpg',
            '/images/Beauty/Anya/Anya9.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'kate',
        genre: 'beauty',
        titleImg: '/images/thumbnails/kate.png',
        images: [
            '/images/Beauty/Kate/Kate0.jpg', 
            '/images/Beauty/Kate/Kate1.jpg',
            '/images/Beauty/Kate/Kate2.jpg',
            '/images/Beauty/Kate/Kate3.jpg',
            '/images/Beauty/Kate/Kate4.jpg',
            '/images/Beauty/Kate/Kate5.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'irridesense',
        genre: 'lookbook',
        titleImg: '/images/thumbnails/irridesense.png',
        images: [
            '/images/LookBook/Irridesense/irridesense0.jpg', 
            '/images/LookBook/Irridesense/irridesense1.jpg',
            '/images/LookBook/Irridesense/irridesense2.jpg',
            '/images/LookBook/Irridesense/irridesense3.jpg',
            '/images/LookBook/Irridesense/irridesense4.jpg',
            '/images/LookBook/Irridesense/irridesense5.jpg',
            '/images/LookBook/Irridesense/irridesense6.jpg',
            '/images/LookBook/Irridesense/irridesense7.jpg',
            '/images/LookBook/Irridesense/irridesense8.jpg',
            '/images/LookBook/Irridesense/irridesense9.jpg',
            '/images/LookBook/Irridesense/irridesense10.jpg',
            '/images/LookBook/Irridesense/irridesense11.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'sonyaGrace',
        genre: 'modeltests',
        titleImg: '/images/thumbnails/sonya.png',
        images: [
            '/images/ModelTests/SonyaGrace/Sonya0.jpg',
            '/images/ModelTests/SonyaGrace/Sonya1.jpg',
            '/images/ModelTests/SonyaGrace/Sonya2.jpg',
            '/images/ModelTests/SonyaGrace/Sonya3.jpg', 
            '/images/ModelTests/SonyaGrace/Sonya4.jpg',
            '/images/ModelTests/SonyaGrace/Sonya5.jpg',
            '/images/ModelTests/SonyaGrace/Sonya6.jpg',
            '/images/ModelTests/SonyaGrace/Sonya7.jpg',
            '/images/ModelTests/SonyaGrace/Sonya8.jpg', 
            '/images/ModelTests/SonyaGrace/Sonya9.jpg',
            '/images/ModelTests/SonyaGrace/Sonya10.jpg',
            '/images/ModelTests/SonyaGrace/Sonya11.jpg',
            '/images/ModelTests/SonyaGrace/Sonya12.jpg',
            '/images/ModelTests/SonyaGrace/Sonya13.jpg', 
            '/images/ModelTests/SonyaGrace/Sonya14.jpg',
            '/images/ModelTests/SonyaGrace/Sonya15.jpg',
            '/images/ModelTests/SonyaGrace/Sonya16.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'leesha',
        genre: 'lookbook',
        titleImg: '/images/thumbnails/leesha.png',
        images: [
            '/images/LookBook/Leesha/Leesha0.jpg',
            '/images/LookBook/Leesha/Leesha1.jpg',
            '/images/LookBook/Leesha/Leesha2.jpg',
            '/images/LookBook/Leesha/Leesha3.jpg', 
            '/images/LookBook/Leesha/Leesha4.jpg',
            '/images/LookBook/Leesha/Leesha5.jpg',
            '/images/LookBook/Leesha/Leesha6.jpg',
            '/images/LookBook/Leesha/Leesha7.jpg',
            '/images/LookBook/Leesha/Leesha8.jpg',
            '/images/LookBook/Leesha/Leesha9.jpg',
            '/images/LookBook/Leesha/Leesha10.jpg',
            '/images/LookBook/Leesha/Leesha11.jpg',
            '/images/LookBook/Leesha/Leesha12.jpg',
            '/images/LookBook/Leesha/Leesha13.jpg',
            '/images/LookBook/Leesha/Leesha14.jpg',
            '/images/LookBook/Leesha/Leesha15.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'anastasia',
        genre: 'modeltests',
        titleImg: '/images/thumbnails/anastasia.png',
        images: [
            '/images/ModelTests/Anastasia/Anastasia0.jpg',
            '/images/ModelTests/Anastasia/Anastasia1.jpg',
            '/images/ModelTests/Anastasia/Anastasia2.jpg',
            '/images/ModelTests/Anastasia/Anastasia3.jpg', 
            '/images/ModelTests/Anastasia/Anastasia4.jpg',
            '/images/ModelTests/Anastasia/Anastasia5.jpg',
            '/images/ModelTests/Anastasia/Anastasia6.jpg',
            '/images/ModelTests/Anastasia/Anastasia7.jpg',
            '/images/ModelTests/Anastasia/Anastasia8.jpg', 
            '/images/ModelTests/Anastasia/Anastasia9.jpg',
            '/images/ModelTests/Anastasia/Anastasia10.jpg',
            '/images/ModelTests/Anastasia/Anastasia11.jpg',
            '/images/ModelTests/Anastasia/Anastasia12.jpg',
            '/images/ModelTests/Anastasia/Anastasia13.jpg', 
            '/images/ModelTests/Anastasia/Anastasia14.jpg',
            '/images/ModelTests/Anastasia/Anastasia15.jpg',
            '/images/ModelTests/Anastasia/Anastasia16.jpg',
            '/images/ModelTests/Anastasia/Anastasia17.jpg',
            '/images/ModelTests/Anastasia/Anastasia18.jpg',
            '/images/ModelTests/Anastasia/Anastasia19.jpg', 
        ],
        wideImages: [''],
    },
    {
        // short
        id: 'catalog3',
        genre: 'catalog',
        titleImg: '/images/thumbnails/catalog_3.png',
        images: [
            '/images/Catalog/Catalog3/3catalog0.jpg', 
            '/images/Catalog/Catalog3/3catalog1.jpg',
            '/images/Catalog/Catalog3/3catalog2.jpg',
            '/images/Catalog/Catalog3/3catalog3.jpg',
            '/images/Catalog/Catalog3/3catalog4.jpg',
            '/images/Catalog/Catalog3/3catalog5.jpg',
        ],
        wideImages: [''],
    },
    {
        // short
        id: 'catalog2',
        genre: 'catalog',
        titleImg: '/images/thumbnails/catalog_2.png',
        images: [
            '/images/Catalog/Catalog2/2catalog0.jpg', 
            '/images/Catalog/Catalog2/2catalog1.jpg',
            '/images/Catalog/Catalog2/2catalog2.jpg',
            '/images/Catalog/Catalog2/2catalog3.jpg',
            '/images/Catalog/Catalog2/2catalog4.jpg',
            '/images/Catalog/Catalog2/2catalog5.jpg',
            '/images/Catalog/Catalog2/2catalog6.jpg',
            '/images/Catalog/Catalog2/2catalog7.jpg',
            '/images/Catalog/Catalog2/2catalog8.jpg',
            '/images/Catalog/Catalog2/2catalog9.jpg',
            '/images/Catalog/Catalog2/2catalog10.jpg',
            '/images/Catalog/Catalog2/2catalog11.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'lisaGrace',
        genre: 'modeltests',
        titleImg: '/images/thumbnails/lisa.png',
        images: [
            '/images/ModelTests/LisaGrace/Lisa0.jpg',
            '/images/ModelTests/LisaGrace/Lisa1.jpg',
            '/images/ModelTests/LisaGrace/Lisa2.jpg',
            '/images/ModelTests/LisaGrace/Lisa3.jpg', 
            '/images/ModelTests/LisaGrace/Lisa4.jpg',
            '/images/ModelTests/LisaGrace/Lisa5.jpg',
            '/images/ModelTests/LisaGrace/Lisa6.jpg',
            '/images/ModelTests/LisaGrace/Lisa7.jpg',
            '/images/ModelTests/LisaGrace/Lisa8.jpg', 
            '/images/ModelTests/LisaGrace/Lisa9.jpg',
            '/images/ModelTests/LisaGrace/Lisa10.jpg',
            '/images/ModelTests/LisaGrace/Lisa11.jpg',
            '/images/ModelTests/LisaGrace/Lisa12.jpg',
            '/images/ModelTests/LisaGrace/Lisa13.jpg', 
            '/images/ModelTests/LisaGrace/Lisa14.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'nastya',
        genre: 'modeltests',
        titleImg: '/images/thumbnails/nastya.png',
        images: [
            '/images/ModelTests/Nastya/NastyaModels0.jpg',
            '/images/ModelTests/Nastya/NastyaModels1.jpg',
            '/images/ModelTests/Nastya/NastyaModels2.jpg',
            '/images/ModelTests/Nastya/NastyaModels3.jpg', 
            '/images/ModelTests/Nastya/NastyaModels4.jpg',
            '/images/ModelTests/Nastya/NastyaModels5.jpg',
            '/images/ModelTests/Nastya/NastyaModels6.jpg',
            '/images/ModelTests/Nastya/NastyaModels7.jpg',
            '/images/ModelTests/Nastya/NastyaModels8.jpg', 
            '/images/ModelTests/Nastya/NastyaModels9.jpg',
            '/images/ModelTests/Nastya/NastyaModels10.jpg',
            '/images/ModelTests/Nastya/NastyaModels11.jpg',
            '/images/ModelTests/Nastya/NastyaModels12.jpg',
            '/images/ModelTests/Nastya/NastyaModels13.jpg', 
            '/images/ModelTests/Nastya/NastyaModels14.jpg',
            '/images/ModelTests/Nastya/NastyaModels15.jpg',
            '/images/ModelTests/Nastya/NastyaModels16.jpg',
            '/images/ModelTests/Nastya/NastyaModels17.jpg',
            '/images/ModelTests/Nastya/NastyaModels18.jpg',
            '/images/ModelTests/Nastya/NastyaModels19.jpg',
            '/images/ModelTests/Nastya/NastyaModels20.jpg',
        ],
        wideImages: [''],
    },
    {
        id: 'catalog1',
        genre: 'catalog',
        titleImg: '/images/thumbnails/catalog_1.png',
        images: [
            '/images/Catalog/Catalog1/catalog1_0.jpg', 
            '/images/Catalog/Catalog1/catalog1_1.jpg',
            '/images/Catalog/Catalog1/catalog1_2.jpg',
            '/images/Catalog/Catalog1/catalog1_3.jpg',
            '/images/Catalog/Catalog1/catalog1_4.jpg',
            '/images/Catalog/Catalog1/catalog1_5.jpg',
            '/images/Catalog/Catalog1/catalog1_6.jpg',
            '/images/Catalog/Catalog1/catalog1_7.jpg',
        ],
        wideImages: [''],
    },
    {
        // short
        id: 'items1',
        genre: 'items',
        titleImg: '/images/thumbnails/items.png',
        images: [
            '/images/Items/Items1/Items1_0.jpg',
            '/images/Items/Items1/Items1_1.jpg',
            '/images/Items/Items1/Items1_2.jpg',
            '/images/Items/Items1/Items1_3.jpg', 
            '/images/Items/Items1/Items1_4.jpg',
            '/images/Items/Items1/Items1_5.jpg',
            '/images/Items/Items1/Items1_6.jpg',
            '/images/Items/Items1/Items1_7.jpg',
            '/images/Items/Items1/Items1_8.jpg',
            '/images/Items/Items1/Items1_9.jpg',
            '/images/Items/Items1/Items1_10.jpg',
            '/images/Items/Items1/Items1_11.jpg',
            '/images/Items/Items1/Items1_12.jpg',
            '/images/Items/Items1/Items1_13.jpg'
        ],
        wideImages: [''],
    },
]

